name: whatrthose
channels:
  - pytorch
  - derickl
  - fastai
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - alabaster=0.7.12
  - asn1crypto=0.24.0
  - astor=0.7.1
  - attrs=19.1.0
  - babel=2.6.0
  - backcall=0.1.0
  - bcrypt=3.1.6
  - beautifulsoup4=4.7.1
  - blas=1.0
  - bleach=3.1.0
  - boto3=1.9.111
  - bottleneck=1.2.1
  - c-ares=1.15.0
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - cffi=1.12.2
  - click=7.0
  - cryptography=2.6.1
  - cymem=2.0.2
  - cytoolz=0.9.0.1
  - dataclasses=0.6
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.5.0
  - dill=0.2.9
  - docutils=0.14
  - entrypoints=0.3
  - expat=2.2.6
  - fastai=1.0.51
  - fastprogress=0.1.21
  - flask=1.0.2
  - flask-login=0.4.1
  - flask-sqlalchemy=2.3.2
  - flask-wtf=0.14.2
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gettext=0.19.8.1
  - glib=2.56.2
  - gmp=6.1.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.9.0
  - hdf5=1.10.4
  - icu=58.2
  - imagesize=1.1.0
  - intel-openmp=2019.3
  - ipykernel=5.1.0
  - ipython=7.3.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - itsdangerous=1.1.0
  - jedi=0.13.3
  - jinja2=2.10.1
  - jmespath=0.9.4
  - jpeg=9b
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - keras-applications=1.0.7
  - keras-preprocessing=1.0.9
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libiconv=1.15
  - libopenblas=0.3.3
  - libpng=1.6.36
  - libprotobuf=3.6.1
  - libsodium=1.0.16
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libxml2=2.9.9
  - markdown=3.1
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2019.3
  - msgpack-numpy=0.4.3.2
  - msgpack-python=0.6.1
  - murmurhash=1.0.2
  - nbconvert=5.4.1
  - nbformat=4.4.0
  - ncurses=6.1
  - ninja=1.9.0
  - nomkl=3.0
  - notebook=5.7.6
  - numexpr=2.6.9
  - numpy-base=1.16.2
  - olefile=0.46
  - openssl=1.1.1b
  - packaging=19.0
  - pandas=0.24.2
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - paramiko=2.4.2
  - parso=0.3.4
  - pbr=5.1.3
  - pcre=8.43
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pip=19.0.3
  - plac=0.9.6
  - preshed=2.0.1
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - pyasn1=0.4.5
  - pycparser=2.19
  - pygments=2.3.1
  - pynacl=1.3.0
  - pyopenssl=19.0.0
  - pyparsing=2.3.1
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - pysocks=1.6.8
  - python=3.7.1
  - python-dateutil=2.8.0
  - python-dotenv=0.10.1
  - pytorch=1.0.1
  - pytz=2018.9
  - pyzmq=18.0.0
  - qt=5.9.7
  - qtconsole=4.4.3
  - readline=7.0
  - regex=2018.01.10
  - s3transfer=0.2.0
  - send2trash=1.5.0
  - setuptools=40.8.0
  - simplejson=3.16.0
  - snowballstemmer=1.2.1
  - soupsieve=1.8
  - spacy=2.0.18
  - sphinx=1.8.5
  - sphinxcontrib=1.0
  - sphinxcontrib-websupport=1.1.0
  - sqlalchemy=1.3.1
  - sqlite=3.27.2
  - tensorboard=1.13.1
  - tensorflow=1.13.1
  - tensorflow-base=1.13.1
  - tensorflow-estimator=1.13.0
  - terminado=0.8.1
  - testpath=0.4.2
  - thinc=6.12.1
  - tk=8.6.8
  - toolz=0.9.0
  - torchvision=0.2.2
  - tornado=6.0.1
  - tqdm=4.31.1
  - traitlets=4.3.2
  - typing=3.6.4
  - ujson=1.35
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.14.1
  - wheel=0.33.1
  - widgetsnbextension=3.4.2
  - wrapt=1.10.11
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.7.1
    - autopep8==1.4.3
    - awscli==1.16.140
    - awsebcli==3.15.0
    - blessed==1.15.0
    - botocore==1.12.130
    - cached-property==1.5.1
    - cement==2.8.2
    - chardet==3.0.4
    - colorama==0.3.9
    - cycler==0.10.0
    - docker==3.7.2
    - docker-compose==1.23.2
    - docker-pycreds==0.4.0
    - dockerpty==0.4.1
    - docopt==0.6.2
    - future==0.16.0
    - gast==0.2.2
    - grpcio==1.19.0
    - idna==2.7
    - jsonschema==2.6.0
    - keras==2.2.4
    - kiwisolver==1.0.1
    - lxml==4.3.3
    - matplotlib==3.0.3
    - mock==2.0.0
    - numpy==1.16.2
    - nvidia-ml-py3==7.352.0
    - opencv-python==4.1.0.25
    - pathspec==0.5.9
    - pillow==5.4.1
    - pipenv==2018.11.26
    - protobuf==3.7.1
    - pycodestyle==2.5.0
    - pyqt5==5.12.1
    - pyqt5-sip==4.19.15
    - pyyaml==5.1
    - requests==2.20.1
    - rsa==3.4.2
    - scipy==1.2.1
    - selenium==3.141.0
    - semantic-version==2.5.0
    - sip==4.19.8
    - six==1.11.0
    - termcolor==1.1.0
    - texttable==0.9.1
    - urllib3==1.24.1
    - virtualenv==16.4.3
    - virtualenv-clone==0.5.1
    - websocket-client==0.56.0
    - wtforms==2.2.1

